from functools import reduce
from typing import Tuple, Any
import itertools
# inp = [x.strip() for x in open("day-10/input1.txt").readlines()]
inp = [x.strip() for x in open("day-11/example.txt").readlines()]

# class Node:
#     def __init__(self, value, children):
#         self.value = value
#         self.children: set[Node] = set()
        

#     def __str__(self):
#         return self._to_string(set())

#     def _to_string(self, visited):
#         if self in visited:
#             return f"Node({self.value}, ...)"  # cycle reference
#         visited.add(self)
#         children_str = ", ".join(c._to_string(visited) for c in self.children)
#         return f"Node({self.value}, [{children_str}])"
    # generated by opus 4.5
    # def graph_str(self):
    #     visited = set()
    #     lines = []
    #     self._collect_edges(visited, lines)
    #     return "\n".join(lines)

    # # generated by opus 4.5
    # def _collect_edges(self, visited, lines):
    #     if self in visited:
    #         return
    #     visited.add(self)
    #     for child in self.children:
    #         lines.append(f"{self.value} -> {child.value}")
    #         child._collect_edges(visited, lines)


# class Graph:
#     def __init__(self):
#         self.nodes = []

#     add_node(parent: )

    # if aa == "you":
    #     inpn.insert(0, (aa, bb))
    # else:
    #     inpn.append((aa,bb))


# a: list[Node] = []
# p = Node("you", [])

# a.append(p)


# def get_node(value: str) -> Node | None:
#     for x in a:
#         if x.value == value:
#             return x
#     return None

# for x in inpn:
#     print(x)
#     n = get_node(x[0])
#     if n == None:
#         n = Node(x[0], [])

#     print("from node", n)
#     for x1 in x[1]:
#         cn = get_node(x1)
#         if cn == None:
#             cn = Node(x1, [])

#         n.children.add(cn)

#         print("child", cn)
#     print("parent after: ", n)


# print(p)

g = {}

inpn = []
for _x in range(len(inp)):
    x = inp[_x]
    x1 = x.split(":")
    aa = x1[0]
    bb = x1[1].split(" ")[1:]
    g[aa] = bb

print(g)


seen = []
start = "you"
t = 0
c = ""


# def try_find(f, to):
    

    


# while True:
